<?php
// $Id: extension_settings.install

/**
* Implementation of hook_install()
 * This is just a place holder as the module doesn't require this hook
*/
/*function extension_settings_install() {

}*/

/**
* Implementation of hook_uninstall()
*/
function extension_settings_uninstall() {
  // Remove the module from the system table
  db_delete('system')
    ->condition('name', 'extension_settings');
  db_delete('variable')
    ->condition('name', 'extension_settings_%', 'LIKE');
}