<?php
// $Id: extension_settings.module 
/**
 * Extension Settings
 * Helper module for EESC managed Drupal sites.
 * This module provides configuration settings.
 */
 
 
/**
 * Implementation of hook_init().
 */
function extension_settings_init() {
  drupal_add_css(drupal_get_path('module', 'extension_settings') .'/css/ggai.css');
  drupal_add_css(drupal_get_path('module', 'extension_settings') .'/css/extension_settings.css');
}

/**
 * Implementation of hook_help()
 * Provide online user help.
 *
 * @param $path
 * @param $arg
 * @return
 *   Help text
 */
function extension_settings_help($path, $arg) {
  switch ($path) {
    case 'admin/settings/extension_settings':
      $output = file_get_contents(drupal_get_path('module', 'extension_settings') .'/README.txt');
       return '<div>'. check_plain($output) .'</div>';
    case 'admin/help#extension_settings':
      return '<p>'. t('The Extension Settings module provides common blocks and custom site configuration settings.') .'</p>';
    default:
      return '';
  }
}

/**
 * Implementation of hook_perm().
 */
function extension_settings_perm() {
  $extension_permissions[] = 'administer extension settings';
  $extension_permissions[] = 'administer extension global content';
  $extension_permissions[] = 'administer extension banners';
  return $extension_permissions;
}

/**
 * Implementation of hook_menu().
 */
function extension_settings_menu() {
  $items = array();
  $items['admin/settings/extension'] = array(
    'title' => t('Extension settings'),
    'description' => t('Administer settings related to the Extension Settings module.'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('extension_settings_admin_settings'),
    'access arguments' => array('administer extension settings'),
    'file' => 'includes/extension_settings.admin.inc',
    'type' => MENU_NORMAL_ITEM,
  );
  $items['admin/settings/extension/admin'] = array(
    'title' => t('Extension settings'),
    'description' => t('Administer settings related to the Extension Settings module.'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('extension_settings_admin_settings'),
    'access arguments' => array('administer extension settings'),
    'weight' => 1,
    'file' => 'includes/extension_settings.admin.inc',
    'type' => MENU_DEFAULT_LOCAL_TASK,
  );
  $items['admin/settings/extension/banners'] = array(
    'title' => t('Banners'),
    'description' => t('Administer Extension banners.'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('extension_settings_banners'),
    'access arguments' => array('administer extension banners'),
    'weight' => 2,
    'file' => 'includes/extension_settings.banners.inc',
    'type' => MENU_LOCAL_TASK,
  );
  $items['admin/settings/extension/global'] = array(
    'title' => t('Global content'),
    'description' => t('Administer global content accross all extension sites.'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('extension_settings_global_emergency'),
    'access arguments' => array('administer extension global content'),
    'file' => 'includes/extension_settings.global.emergency.inc',
    'type' => MENU_LOCAL_TASK,
  );
  $items['admin/settings/extension/global/emergency'] = array(
    'title' => t('Emergency Information'),
    'description' => t('Global content for Emergency Information.'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('extension_settings_global_emergency'),
    'access arguments' => array('administer extension global content'),
    'file' => 'includes/extension_settings.global.emergency.inc',
    'type' => MENU_DEFAULT_LOCAL_TASK,
  );
  $items['admin/settings/extension/global/block2'] = array(
    'title' => t('Block 2'),
    'description' => t('Global content for block 2.'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('extension_settings_global_block2'),
    'access arguments' => array('administer extension global content'),
    'weight' => 2,
    'file' => 'includes/extension_settings.global.block2.inc',
    'type' => MENU_LOCAL_TASK,
  );
  $items['globalblock1'] = array(
    'title' => t('Emergency Information'),
    'page callback' => 'extension_settings_global_block_1_code',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );
  $items['globalblock2'] = array(
    'title' => t('Global Content block 2'),
    'page callback' => 'extension_settings_global_block_2_code',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );
  return $items;
}

/**
* Implementation of hook_block().
* @param string $op one of "list", "view", "save" and "configure"
* @param integer $delta code to identify the block
*/

function extension_settings_block($op = 'list', $delta = 0, $edit = array()) {
  if ($op == 'list') {
    $blocks[0]['info'] = t('Life: Get good at it sidebar links');
    $blocks[1]['info'] = t('Badge - Gardening');
    $blocks[2]['info'] = t('Badge - Trees and Woodlands');
    $blocks[3]['info'] = t('Badge - Food Preservation');
    $blocks[4]['info'] = t('Badge - Food and Nutrition');
    $blocks[5]['info'] = t('Badge - Family and Youth');
    $blocks[6]['info'] = t('Badge - Health and Wellness');
    $blocks[7]['info'] = t('Badge - Small Farms');
    $blocks[8]['info'] = t('Calendar Block');
    $blocks[9]['info'] = t('Emergency Information Block');
    $blocks[10]['info'] = t('Global Content Block 2');
		$blocks[11]['info'] = t('Extension Neapolitan Block');
		$blocks[12]['info'] = t('Extension Banners Block');
		
    return $blocks;
  } else if ($op == 'view') {
    $block = array();
    switch ($delta) {
      case 0:
        $ggai_output = '
                    <div id="ggai-block" class="ggai-block">
					            <div class="ggai-block-header"></div>
					            <div class="wm_sun">
					              <ul>
					                <li class="item-1"><span><a href="http://extension.oregonstate.edu/node/320" title="Gardening: Get Good at It.">Gardening</a></span></li>
					                <li class="item-7"><span><a href="http://extension.oregonstate.edu/node/304" title="Small Farms: Get Good at It.">Small Farms</a></span></li>
					                <li class="item-3"><span><a href="http://extension.oregonstate.edu/node/305" title="Food Preservation: Get Good at It.">Food Preservation</a></span></li>
					                <li class="item-4"><span><a href="http://extension.oregonstate.edu/node/306" title="Food &amp; Nutrition: Get Good at It.">Food &amp; Nutrition</a></span></li>
					                <li class="item-5"><span><a href="http://extension.oregonstate.edu/node/307" title="Family &amp; Youth: Get Good at It.">Family &amp; Youth</a></span></li>
					              	<ul id="ggai_hidden" style="list-style-type: none; margin-left: 0px; display: none;">
														<li class="item-6"><span><a href="http://extension.oregonstate.edu/node/308" title="Health &amp; Wellness: Get Good at It.">Health &amp; Wellness</a></span></li>
						                <li class="item-8"><span><a href="http://extension.oregonstate.edu/node/4407" title="Environment: Get Good at It.">Environment</a></span></li>
														<li class="item-2"><span><a href="http://extension.oregonstate.edu/node/3333" title="Trees &amp; Woodlands: Get Good at It.">Trees &amp; Woodlands</a></span></li>

									</ul>
					              </ul>
								<p style="margin: 0.5em 0 1em -30px;">
					              <a id="ggai_hidden_link" style="color: #E48101; font-weight: normal; 	font-family: Arial, Helvetica, Verdana, '."'Bitstream Vera Sans'".', sans-serif; cursor: pointer;"
									 onclick="javascript: ($('."'#ggai_hidden'".').css('."'display'".') == '."'none'".')? $('."'#ggai_hidden'".').slideDown('."'fast'".', function(){$('."'#ggai_hidden_link'".').html('."'Show less »'".'); $('."'".'.wm_sun'."'".').css('."'".'padding-bottom'."'".', '."'".'40px'."'".');}) : $('."'#ggai_hidden'".').slideUp('."'fast'".', function(){$('."'#ggai_hidden_link'".').html('."'Show more »'".'); $('."'".'.wm_sun'."'".').css('."'".'padding-bottom'."'".', '."'".'30px'."'".');})">Show more »</a>
								</p>
					            </div>
					          </div>
					<!--[if lte IE 8]>
					<style type="text/css">
					#ggai_hidden_link 
					{
						margin-left: 30px;
					}
					#ggai_hidden 
					{
						margin-top: 6px;
					}
					#ggai-block {
						padding-bottom: 0px;
					}
					</style>
					<![endif]-->';
        $block['subject'] = t('');
        $block['content'] = t($ggai_output);
        return $block;
      case 1:
        $badge_content = '<a title="Oregon State University Extension Service: Gardening" href="http://extension.oregonstate.edu/node/320"><img src="http://extension.oregonstate.edu/sites/default/themes/extension/images/badges/extbdg320.gif" width="190" height="52" alt="Oregon State University Extension Service: Gardening badge image" /></a>';
        $block['subject'] = t('');
        $block['content'] = t($badge_content);
        return $block;
      case 2:
        $badge_content = '<a title="Oregon State University Extension Service: Trees &amp; Woodlands" href="http://extension.oregonstate.edu/node/3333"><img src="http://extension.oregonstate.edu/sites/default/themes/extension/images/badges/extbdg3333.gif" width="190" height="52" alt="Oregon State University Extension Service: Trees &amp; Woodlands badge image" /></a>';
        $block['subject'] = t('');
        $block['content'] = t($badge_content);
        return $block;
      case 3:
        $badge_content = '<a title="Oregon State University Extension Service: Food Preservation" href="http://extension.oregonstate.edu/node/305"><img src="http://extension.oregonstate.edu/sites/default/themes/extension/images/badges/extbdg305.gif" width="190" height="52" alt="Oregon State University Extension Service: Food Preservation badge image" /></a>';
        $block['subject'] = t('');
        $block['content'] = t($badge_content);
        return $block;
      case 4:
        $badge_content = '<a title="Oregon State University Extension Service: Food &amp; Nutrition" href="http://extension.oregonstate.edu/node/306"><img src="http://extension.oregonstate.edu/sites/default/themes/extension/images/badges/extbdg306.gif" width="190" height="52" alt="Oregon State University Extension Service: Food &amp; Nutrition badge image" /></a>';
        $block['subject'] = t('');
        $block['content'] = t($badge_content);
        return $block;
      case 5:
        $badge_content = '<a title="Oregon State University Extension Service: Family &amp; Youth" href="http://extension.oregonstate.edu/node/307"><img src="http://extension.oregonstate.edu/sites/default/themes/extension/images/badges/extbdg307.gif" width="190" height="52" alt="Oregon State University Extension Service: Family &amp; Youth badge image" /></a>';
        $block['subject'] = t('');
        $block['content'] = t($badge_content);
        return $block;
      case 6:
        $badge_content = '<a title="Oregon State University Extension Service: Health &amp; Wellness" href="http://extension.oregonstate.edu/node/308"><img src="http://extension.oregonstate.edu/sites/default/themes/extension/images/badges/extbdg308.gif" width="190" height="52" alt="Oregon State University Extension Service: Health &amp; Wellness badge image" /></a>';
        $block['subject'] = t('');
        $block['content'] = t($badge_content);
        return $block;
      case 7:
        $badge_content = '<a title="Oregon State University Extension Service: Small Farms" href="http://extension.oregonstate.edu/node/304"><img src="http://extension.oregonstate.edu/sites/default/themes/extension/images/badges/extbdg304.gif" width="190" height="52" alt="Oregon State University Extension Service: Small Farms badge image" /></a>';
        $block['subject'] = t('');
        $block['content'] = t($badge_content);
        return $block;
      case 8:
        $shortname = variable_get('extension_settings_calendar_shortname', '');
        $lookahead = variable_get('extension_settings_calendar_lookahead', '90');
        $disp_num = variable_get('extension_settings_calendar_numdisplay', '5');
        $teaser = variable_get('extension_settings_calendar_teaser', '15');
        $calendar_output = '';
        $xml_path = 'http://calendar.oregonstate.edu/today+' . $lookahead . '/list/' . $shortname . '/rss20.xml';
        $xml = simplexml_load_file($xml_path);
        $flag = count($xml->channel->item);
        if ($flag != 0) {
          $calendar_output .= '<div id="calendar"><a class="rss" href="';
          $calendar_output .= $xml_path;
          $calendar_output .= '"><img src="http://extension.oregonstate.edu/sites/default/files/images/icons/rss_icon.png" width="15" height="15" /></a>';
        }
        for($i = 0; $i < count($xml->channel->item) && $i < $disp_num; $i++){
          unset($event);
          $event = $xml->channel->item[$i];
          $event_title = $event->title;
          $event_link = $event->link;
          preg_match('/<div(.*?)<\/div>/', $event->description, $matches);
          $dates = strip_tags($matches[0]);
          $event->description = preg_replace('/<div(.*?)<\/div>/', '', $event->description);
          $event_body = preg_split('/\s+/', trim(strip_tags($event->description)), ($teaser + 1));
          if (count($event_body) == $teaser + 1) {
            array_pop($event_body);
            $event_body[] = '&hellip;';
          }
          unset($event);
          $event['allday'] = 0;
          if (preg_match('/\(.*?\)/', $dates) != 0) $event['allday'] = 1;
          $dates = explode(' - ', preg_replace('/\(.*?\)/', '', $dates));
          $event['start'] = strtotime($dates[0]);
          $event['newday'] = 0;
          if (isset($dates[1])) {
            if (preg_match('/(mon)|(tue)|(wed)|(thu)|(fri)|(sat)|(sun)/i', $dates[1]) != 0) {
              $event['newday'] = 1;
            }
            $event['end'] = strtotime($dates[1]);
          }
          $event['date'] = '<span class="start">';
          $event['date'] .= date('M. d, Y', $event['start']) . ' <span class="time">';
          if (!isset($event['end']) && $event['newday'] == 0) {
            $event['date'] .= '(all day)';
          } elseif ($event['allday'] == 1 && $event['newday'] == 1) {
            $event['date'] .= '';
          } else {
            $event['date'] .= date('g:ia', $event['start']);
          }
          $event['date'] .= '</span></span>';
          if (isset($event['end'])) {
            $event['date'] .= ' - <span class="end">';
            if ($event['newday'] == 1) {
              $event['date'] .= date('M. d, Y', $event['end']);
            }
            $event['date'] .= ' <span class="time">';
            if ($event['newday'] == 1 && $event['allday'] == 1) {
              $event['date'] .= '(all day)';
            } else {
              $event['date'] .= date('g:ia', $event['end']);
            }
            $event['date'] .= '</span></span>';
          }
          $event['title'] = $event_title;
          $event['link'] = $event_link;
          $event['body'] = implode(' ', $event_body);
        
          $calendar_output .= '<div class="event"><div class="date">';
          $calendar_output .= $event['date'];
          $calendar_output .= '</div><div class="description"><div class="title"><a href="';
          $calendar_output .= $event['link'];
          $calendar_output .= '">';
          $calendar_output .= $event['title'];
          $calendar_output .= '</a><br /></div><div class="teaser">';
          $calendar_output .= $event['body'];
          $calendar_output .= '</div></div></div>';
        }
        if ($flag != 0) {
          $calendar_output .= '</div><a href="http://calendar.oregonstate.edu/advanced/today+60/';
          $calendar_output .= $shortname;
          $calendar_output .= '">View full calendar</a>';
        }
        $block['subject'] = t('Upcoming Events');
        $block['content'] = $calendar_output;
        return $block;
      case 9:
        $block['subject'] = t('');
        $block['content'] = extension_settings_globalblock_content('1');
        return $block;
      case 10:
        $block['subject'] = t('');
        $block['content'] = extension_settings_globalblock_content('2');
        return $block;
			case 11:
				$neapolitan_output = '<div style="width: 580px; margin: 10px auto 0; padding-bottom: 5px; border-top: 1px dotted #999;"></div>
				<div style="margin: 15px 0; padding: 0 1.5%; border-right: 1px solid #CCC; height: 220px; width: 170px; float: left;">
				<div style="height: 110px;">
				<a style="display: block; width: 106px; margin-left: 0;" href="http://oregonprogress.oregonstate.edu/" title="Oregon&#39;s Agricultural Progress">
				<img src="http://extension.oregonstate.edu/_includes/images/OAP_latest_thumb.jpg" width="81" height="106"/>
				</a>
				</div>
				<div style="width: 150px; margin-left: 0; line-height: 16px; font-size: 12px;">
				<b>Oregon&#39;s Agricultural Progress</b><br/>
				<span style="font-size: 11px;">
				The research magazine for Oregon State University Agricultural Experiment Station
				</span>
				</div>
				</div>
				<div style="margin: 15px 0; padding: 0 1.5%; border-right: 1px solid #CCC; height: 220px; width: 190px; float: left;">
				<div style="height: 98px; margin-top: 12px;">
				<a style="display: block; width: 132px; margin: auto;" href="';
				$neapolitan_output .= (module_exists('extension_ask_expert') == TRUE)? 'ask-an-expert' : 'http://extension.oregonstate.edu/extension-ask-an-expert';
				$neapolitan_output .= '" title="Oregon&#39;s Agricultural Progress">
				<img src="/sites/default/modules/extension_ask_expert/theme/ask-an-expert.png" width="132" height="89"/>
				</a>
				</div>
				<div style="width: 150px; margin: auto; line-height: 16px; font-size: 12px;">
				<b>Ask an Expert</b><br/>
				<span style="font-size: 11px;">
				Addressing real-life questions with research-based answers... Ask an Expert at Oregon State University.
				</span>
				</div>
				</div>
				<div style="margin: 15px 0; padding: 0 1.5%; height: 220px; width: 150px; float: left;">
				<div style="height: 110px;">
				<a style="display: block; width: 118px; margin: auto;" href="http://extension.oregonstate.edu/catalog/" title="Publications">
				<img src="http://extension.oregonstate.edu/_includes/images/pubs_white-bg.jpg" width="118" height="102"/>
				</a>
				</div>
				<div style="width: 150px; margin-left: 10px; line-height: 16px; font-size: 12px;">
				<b>Publications</b><br/>
				<span style="font-size: 11px;">
				OSU Extension&#39;s Publications and Multimedia Catalog.
				</span>
				</div>
				</div>
				<div style="clear: both; height: 10px; width: 1px;"></div>';
	      $block['subject'] = t('');
	      $block['content'] = $neapolitan_output;
	      return $block;
	    case 12:
	      $banner_content = '';
	      $banners = variable_get('extension_settings_banners', '');
	      if ($banners['1']['display'] == 1) {
	        $banner[$banners['1']['weight']] = '<div><img src="' . base_path() . drupal_get_path('module', 'extension_settings') .'/images/gfx_ico_snake.png" /></div>';
	      }
	      if ($banners['2']['display'] == 1) {
	        $banner[$banners['2']['weight']] = '<div><img src="' . base_path() . drupal_get_path('module', 'extension_settings') .'/images/gfx_ico_spade.png" /></div>';
	      }
	      if ($banners['3']['display'] == 1) {
	        $banner[$banners['3']['weight']] = '<div><img src="' . base_path() . drupal_get_path('module', 'extension_settings') .'/images/gfx_ico_pot.png" /></div>';
	      }
	      ksort($banner);
	      $banner_content = implode('', $banner);	      
        $block['subject'] = t('');
        $block['content'] = $banner_content;
        return $block;
    }
  }
}

function extension_settings_globalblock_content($globalblock_id) {
  $fileurl = 'http://extension.oregonstate.edu/globalblock' . $globalblock_id;
  $globaldata = file_get_contents($fileurl);  
  if ($globaldata) {
    $regionslength = strpos($globaldata, '</regions>') - 47;
    $globalregions = explode(',', substr($globaldata, 47, $regionslength));
    $site_region = variable_get('extension_settings_region', '');
    if (in_array($site_region, $globalregions)) {
      $globalcontentstart = strpos($globaldata, '</regions>') + 31;
      if($globalblock_id == '1') {
        $globalblock_content = '<div class="emergency-wrapper"><div class="emergency-wrapper-black"><div class="emergency-info-label">Emergency<br />Information</div></div><div class="emergency-arrow"></div><div class="emergency-info">' . substr($globaldata, $globalcontentstart, -22) . '</div></div>';
      } else {
        $globalblock_content = substr($globaldata, $globalcontentstart, -22);
      }
    }
  } else {
    $globalblock_content = '';
  }
  return $globalblock_content;
}

/**
 * function to remove all given values from an array
*/
function extension_settings_remove_item_by_value($array, $val = '', $preserve_keys = true) {
  if (empty($array) || !is_array($array)) return false;
  if (!in_array($val, $array)) return $array;
  foreach($array as $key => $value) {
    if ($value == $val) unset($array[$key]);
  }
  return ($preserve_keys === true) ? $array : array_values($array);
}

function extension_settings_global_block_1_code() {
  $global_content = variable_get('extension_settings_global_content_1', '');
  if ($global_content == '') {
    return NULL;
  } else {
    $global_content['regions'] = extension_settings_remove_item_by_value($global_content['regions'], '0');
    $xml_data['regions'] = implode(',', $global_content['regions']);
    $xml_data['content'] = $global_content['content'];

    print '<?xml version="1.0" encoding="UTF-8"?>';
    print '<regions>' . $xml_data['regions'] . '</regions>';
    print '<globalblock_content>' . $xml_data['content'] . '</globalblock_content>';
    
    return NULL;
  }
}

function extension_settings_global_block_2_code() {
  $global_content = variable_get('extension_settings_global_content_2', '');
  if ($global_content == '') {
    return NULL;
  } else {
    $global_content['regions'] = extension_settings_remove_item_by_value($global_content['regions'], '0');
    $xml_data['regions'] = implode(',', $global_content['regions']);
    $xml_data['content'] = $global_content['content'];
    
    print '<?xml version="1.0" encoding="UTF-8"?>';
    print '<regions>' . $xml_data['regions'] . '</regions>';
    print '<globalblock_content>' . $xml_data['content'] . '</globalblock_content>';
    
    return NULL;
  }
}

/**
 * Adds a comma seperated list for multivalue text fields
*/

/**
 * Implementation of hook_theme().
 */
function extension_settings_theme() {
 return array(
   'extension_settings_formatter_comma' => array(
     'arguments' => array(
       'element' => NULL,
     ),
   ),
   'extension_settings_banners' => array(
     'arguments' => array(
       'form' => NULL,
      ),
     'file' => 'includes/extension_settings.banners.inc',
   ),
 );
}

/**
 * Implementation of hook_field_formatter_info().
 */
function extension_settings_field_formatter_info() {
 return array(
   'comma' => array(
    'label' => t('Comma separated'), 
    'multiple values' => CONTENT_HANDLE_MODULE, 
    'field types' => array('text'),
   ),
 ); 
}

/**
 * Theme function for Comma separated
 */
function theme_extension_settings_formatter_comma($element) {
 $i=0;
 $items=array();
 while(isset($element[$i])){
  $item=theme_text_formatter_default($element[$i]);
  if(!empty($item)){
   $items[]=$item;
  }
  $i++;
 }
 return implode(', ', $items);
}


/**
* Implementation of hook_form_alter().
*/
function extension_settings_form_alter(&$form, $form_state, $form_id) {
  //$output .= dsm($form);
  switch ($form_id) {
    // This is our form ID.
    case 'page_node_form':
      // remove the Show summary in full view field
      unset($form['body_field']['teaser_include']);
      // remove other unneeded fields
      unset($form['author']);
      unset($form['revision_information']);
    break;
    case 'story_node_form':
      // remove the Show summary in full view field
      unset($form['body_field']['teaser_include']);
      // remove other unneeded fields
      unset($form['author']);
      unset($form['revision_information']);
    break;
    case 'book_node_form':
      // remove the Show summary in full view field
      unset($form['body_field']['teaser_include']);
      // remove other unneeded fields
      unset($form['author']);
      unset($form['revision_information']);
    break;
    case 'google_cse_searchbox_form':
      // remove form options on the form block
      unset($form['sitesearch']);
    break;
    case '_linkit_form':
      $form['link']['link']['#field_suffix'] = NULL;
      $form['link']['link']['#description'] = 'Start typing the name of the page to link to, enter a full URL (http://www.example.com), <b>OR</b> select Browse Server to upload or select a file.';
    break;
  }
}